-- AlterTable
ALTER TABLE "PricingPlan" ADD COLUMN     "aiDigitalizationLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "aiExamPredictionLimit" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "aiInsightLimit" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "aiQuizGenLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "aiReceiptScanLimit" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "aiSkripsweetLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "aiTodoParseLimit" INTEGER NOT NULL DEFAULT 10;
