-- AlterTable
ALTER TABLE "User" ADD COLUMN     "address" TEXT,
ADD COLUMN     "bio" TEXT,
ADD COLUMN     "birthDate" TIMESTAMP(3),
ADD COLUMN     "city" TEXT,
ADD COLUMN     "currentSemester" INTEGER,
ADD COLUMN     "dailyStudyHours" DOUBLE PRECISION,
ADD COLUMN     "enrollmentYear" INTEGER,
ADD COLUMN     "faculty" TEXT,
ADD COLUMN     "gender" TEXT,
ADD COLUMN     "gpa" DOUBLE PRECISION,
ADD COLUMN     "hobbies" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "interests" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "learningStyle" TEXT,
ADD COLUMN     "major" TEXT,
ADD COLUMN     "nickname" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "preferredLanguage" TEXT DEFAULT 'id',
ADD COLUMN     "province" TEXT,
ADD COLUMN     "skills" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "socialLinks" JSONB,
ADD COLUMN     "studentId" TEXT,
ADD COLUMN     "studyGoals" TEXT,
ADD COLUMN     "university" TEXT;
